version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3305:3306"
        networks:
            - task_man
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
        networks:
            - task_man
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
        ports:
            - "8002:80"
        networks:
            - task_man
        env_file:
            - .env.nginx.local

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    task_man:
